name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:    # allows you to run it manually

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: shalinikannan23
          outputs: |
            ./dist/github-contribution-grid-snake.svg
            ./dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push generated files
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
